### ISSUE TITLE
No outputs at lesson 23

### ISSUE THREAD

**Issue by manabuishii** [common-workflow-language/user_guide#129]
In lesson 23 
There are 3 cwl files.
But every cwl files have just `outputs: []`

Rabix Composer can not execute these cwl correctly.

It shoud have something.

For examle.

*scatter-workflow.cwl*

```
#!/usr/bin/env cwl-runner

cwlVersion: v1.0
class: Workflow

requirements:
  ScatterFeatureRequirement: {}

inputs:
  message_array: string[] 

steps:
  echo:
    run: 1st-tool.cwl
    scatter: message
    in:
      message: message_array
    out: []

outputs: []
```
