### ISSUE TITLE
document NetworkAccess

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/user_guide#249]
https://www.commonwl.org/v1.2/CommandLineTool.html#NetworkAccess

**Comment by swzCuroverse** [comment]
@Fienne here is an example -- https://github.com/arvados/lightning/blob/21d6e8843c29ee1f6c8ffdf867fda49d12378b40/cwl/lightning/lightning-anno2vcf.cwl

It has a bunch of Arvados specific flags but you can see how it is used.  If we can think of a simple command line tools that requires the network, that might be easiest.  Let me come up with one and then you can write a simple cwl tool for it.

**Comment by swzCuroverse** [comment]
@Fienne I wrote a simple example using Curl and downloading the page with links to the CWL standards.

```
cwlVersion: v1.2
class: CommandLineTool

requirements:
  NetworkAccess:
    networkAccess: true

baseCommand: curl 

stdout: download.html 

inputs:
  url:
    type: string
    inputBinding:
       position: 1

outputs:
  out:
    type: File 
    outputBinding:
      glob: download.html
```
